"""
IDE Sync - Promoted from DuggerGitTools to DuggerLinkTools

Universal AI IDE persona synchronization across all development environments.
Syncs AGENT_PROTOCOL.md + PERSONA.md to all supported IDE configurations.
"""

import json
from dataclasses import dataclass
from pathlib import Path
from typing import List

from loguru import logger


@dataclass
class IDESyncResult:
    """Result of IDE sync operation."""
    
    ide_name: str
    file_path: Path
    created: bool
    updated: bool
    skipped: bool
    error: str | None = None


class IDESync:
    """Universal IDE persona and protocol synchronization.
    
    Syncs AGENT_PROTOCOL.md + PERSONA.md to:
    - Cursor (.cursorrules)
    - Windsurf (.windsurfrules)
    - Antigravity (.antigravity/instructions.md)
    - Amazon Kiro (.kiro/context.json)
    - Generic (.ai-rules)
    """

    def __init__(self, project_root: Path):
        """Initialize IDESync.
        
        Args:
            project_root: Project root directory
        """
        self.project_root = project_root
        self.logger = logger.bind(component="IDESync")

        self.agent_protocol_path = project_root / "AGENT_PROTOCOL.md"
        self.persona_path = project_root / "PLANNING" / "PERSONA.md"

    def _load_source_docs(self) -> tuple[str, str]:
        """Load AGENT_PROTOCOL.md and PERSONA.md.
        
        Returns:
            Tuple of (protocol_content, persona_content)
        """
        protocol = ""
        persona = ""

        if self.agent_protocol_path.exists():
            with self.agent_protocol_path.open("r", encoding="utf-8") as f:
                protocol = f.read()
        else:
            self.logger.warning("AGENT_PROTOCOL.md not found")

        if self.persona_path.exists():
            with self.persona_path.open("r", encoding="utf-8") as f:
                persona = f.read()
        else:
            self.logger.warning("PLANNING/PERSONA.md not found")

        return protocol, persona

    def generate_master_instructions(self) -> str:
        """Generate master instructions from protocol + persona.
        
        Returns:
            Combined instructions markdown
        """
        protocol, persona = self._load_source_docs()

        master = f"""# AI Agent Instructions

**Generated by DuggerLinkTools IDESync**

This project uses the DuggerLinkTools universal DevOps framework. The following instructions define both **who you're working with** (Persona) and **how to work** (Protocol).

---

{persona}

---

{protocol}

---

## Summary

**Your Mission**: 
- Maintain SOLID architecture
- Use deterministic logic (no AI hallucinations in production)
- Sync documentation automatically
- Scan for security issues proactively
- Organize projects without breaking existing code

**Quick Start**:
```bash
dgt-add scan           # Extract TODOs
dgt-add audit          # Run security scan
dgt commit             # Auto-format + commit
```

**Remember**: You're working with a senior engineer who values **speed, determinism, and zero-jargon communication**. Build tools, not toys.
"""

        return master

    def sync_cursor(self, overwrite: bool = False) -> IDESyncResult:
        """Sync to Cursor (.cursorrules).
        
        Args:
            overwrite: Overwrite existing file
            
        Returns:
            IDESyncResult
        """
        target_path = self.project_root / ".cursorrules"

        if target_path.exists() and not overwrite:
            return IDESyncResult(
                ide_name="Cursor",
                file_path=target_path,
                created=False,
                updated=False,
                skipped=True,
            )

        try:
            existed_before = target_path.exists()
            master = self.generate_master_instructions()

            with target_path.open("w", encoding="utf-8") as f:
                f.write(master)

            created = not existed_before

            return IDESyncResult(
                ide_name="Cursor",
                file_path=target_path,
                created=created,
                updated=not created,
                skipped=False,
            )

        except Exception as e:
            return IDESyncResult(
                ide_name="Cursor",
                file_path=target_path,
                created=False,
                updated=False,
                skipped=False,
                error=str(e),
            )

    def sync_windsurf(self, overwrite: bool = False) -> IDESyncResult:
        """Sync to Windsurf (.windsurfrules).
        
        Args:
            overwrite: Overwrite existing file
            
        Returns:
            IDESyncResult
        """
        target_path = self.project_root / ".windsurfrules"

        if target_path.exists() and not overwrite:
            return IDESyncResult(
                ide_name="Windsurf",
                file_path=target_path,
                created=False,
                updated=False,
                skipped=True,
            )

        try:
            existed_before = target_path.exists()
            master = self.generate_master_instructions()

            with target_path.open("w", encoding="utf-8") as f:
                f.write(master)

            created = not existed_before

            return IDESyncResult(
                ide_name="Windsurf",
                file_path=target_path,
                created=created,
                updated=not created,
                skipped=False,
            )

        except Exception as e:
            return IDESyncResult(
                ide_name="Windsurf",
                file_path=target_path,
                created=False,
                updated=False,
                skipped=False,
                error=str(e),
            )

    def sync_antigravity(self, overwrite: bool = False) -> IDESyncResult:
        """Sync to Antigravity (.antigravity/instructions.md).
        
        Args:
            overwrite: Overwrite existing file
            
        Returns:
            IDESyncResult
        """
        antigravity_dir = self.project_root / ".antigravity"
        target_path = antigravity_dir / "instructions.md"

        if target_path.exists() and not overwrite:
            return IDESyncResult(
                ide_name="Antigravity",
                file_path=target_path,
                created=False,
                updated=False,
                skipped=True,
            )

        try:
            # Create directory if needed
            antigravity_dir.mkdir(exist_ok=True)
            existed_before = target_path.exists()

            master = self.generate_master_instructions()

            with target_path.open("w", encoding="utf-8") as f:
                f.write(master)

            created = not existed_before

            return IDESyncResult(
                ide_name="Antigravity",
                file_path=target_path,
                created=created,
                updated=not created,
                skipped=False,
            )

        except Exception as e:
            return IDESyncResult(
                ide_name="Antigravity",
                file_path=target_path,
                created=False,
                updated=False,
                skipped=False,
                error=str(e),
            )

    def sync_kiro(self, overwrite: bool = False) -> IDESyncResult:
        """Sync to Amazon Kiro (.kiro/context.json).
        
        Args:
            overwrite: Overwrite existing file
            
        Returns:
            IDESyncResult
        """
        kiro_dir = self.project_root / ".kiro"
        target_path = kiro_dir / "context.json"

        if target_path.exists() and not overwrite:
            return IDESyncResult(
                ide_name="Kiro",
                file_path=target_path,
                created=False,
                updated=False,
                skipped=True,
            )

        try:
            # Create directory if needed
            kiro_dir.mkdir(exist_ok=True)
            existed_before = target_path.exists()

            # Generate context as JSON
            master = self.generate_master_instructions()

            context = {
                "version": "1.0",
                "project_type": "duggerlink",
                "instructions": master,
                "generated_by": "DuggerLinkTools IDESync",
                "sync_source": [
                    "AGENT_PROTOCOL.md",
                    "PLANNING/PERSONA.md",
                ],
            }

            with target_path.open("w", encoding="utf-8") as f:
                json.dump(context, f, indent=2)

            created = not existed_before

            return IDESyncResult(
                ide_name="Kiro",
                file_path=target_path,
                created=created,
                updated=not created,
                skipped=False,
            )

        except Exception as e:
            return IDESyncResult(
                ide_name="Kiro",
                file_path=target_path,
                created=False,
                updated=False,
                skipped=False,
                error=str(e),
            )

    def sync_generic(self, overwrite: bool = False) -> IDESyncResult:
        """Sync to generic AI (.ai-rules).
        
        Args:
            overwrite: Overwrite existing file
            
        Returns:
            IDESyncResult
        """
        target_path = self.project_root / ".ai-rules"

        if target_path.exists() and not overwrite:
            return IDESyncResult(
                ide_name="Generic",
                file_path=target_path,
                created=False,
                updated=False,
                skipped=True,
            )

        try:
            existed_before = target_path.exists()
            master = self.generate_master_instructions()

            with target_path.open("w", encoding="utf-8") as f:
                f.write(master)

            created = not existed_before

            return IDESyncResult(
                ide_name="Generic",
                file_path=target_path,
                created=created,
                updated=not created,
                skipped=False,
            )

        except Exception as e:
            return IDESyncResult(
                ide_name="Generic",
                file_path=target_path,
                created=False,
                updated=False,
                skipped=False,
                error=str(e),
            )

    def sync_all_ides(self, overwrite: bool = False) -> List[IDESyncResult]:
        """Sync to all supported IDEs.
        
        Args:
            overwrite: Overwrite existing files
            
        Returns:
            List of IDESyncResult
        """
        self.logger.info("Syncing to all IDEs...")

        results = [
            self.sync_cursor(overwrite),
            self.sync_windsurf(overwrite),
            self.sync_antigravity(overwrite),
            self.sync_kiro(overwrite),
            self.sync_generic(overwrite),
        ]

        # Log summary
        created_count = sum(1 for r in results if r.created)
        updated_count = sum(1 for r in results if r.updated)
        skipped_count = sum(1 for r in results if r.skipped)
        error_count = sum(1 for r in results if r.error)

        self.logger.info(
            f"IDE sync complete: {created_count} created, "
            f"{updated_count} updated, {skipped_count} skipped, {error_count} errors",
        )

        return results